export const initialSchemaMigration = {
  id: '001_initial_schema',
  description: 'Estrutura inicial da biblioteca',
  statements: [
    `CREATE TABLE IF NOT EXISTS users (
      id TEXT PRIMARY KEY,
      nome TEXT NOT NULL,
      email TEXT NOT NULL UNIQUE,
      role TEXT NOT NULL,
      ativo BOOLEAN NOT NULL DEFAULT TRUE,
      senha_hash TEXT NOT NULL,
      turma TEXT,
      token_professor_id TEXT,
      ultimo_acesso TEXT,
      criado_em TEXT NOT NULL
    )`,
    `CREATE TABLE IF NOT EXISTS books (
      id TEXT PRIMARY KEY,
      numero_tombo TEXT,
      titulo TEXT NOT NULL,
      autor TEXT NOT NULL,
      categoria TEXT NOT NULL,
      quantidade INTEGER NOT NULL,
      quantidade_disponivel INTEGER NOT NULL,
      classificacao INTEGER NOT NULL,
      faixa_escolar TEXT NOT NULL,
      dias_leitura INTEGER NOT NULL,
      descricao TEXT NOT NULL,
      capa TEXT NOT NULL
    )`,
    `CREATE TABLE IF NOT EXISTS loans (
      id TEXT PRIMARY KEY,
      livro_id TEXT NOT NULL,
      aluno_id TEXT NOT NULL,
      token TEXT NOT NULL UNIQUE,
      status TEXT NOT NULL,
      data_pedido TEXT NOT NULL,
      data_devolucao_prevista TEXT,
      data_devolucao TEXT,
      observacao TEXT
    )`,
    `CREATE TABLE IF NOT EXISTS suggestions (
      id TEXT PRIMARY KEY,
      professor_id TEXT NOT NULL,
      livro_id TEXT NOT NULL,
      turma TEXT NOT NULL,
      mensagem TEXT NOT NULL,
      criado_em TEXT NOT NULL
    )`,
    `CREATE TABLE IF NOT EXISTS tickets (
      id TEXT PRIMARY KEY,
      usuario_id TEXT NOT NULL,
      assunto TEXT NOT NULL,
      mensagem TEXT NOT NULL,
      status TEXT NOT NULL,
      resposta TEXT,
      criado_em TEXT NOT NULL
    )`,
    `CREATE TABLE IF NOT EXISTS teacher_tokens (
      id TEXT PRIMARY KEY,
      token TEXT NOT NULL UNIQUE,
      descricao TEXT NOT NULL,
      turmas_permitidas TEXT NOT NULL,
      usado BOOLEAN NOT NULL DEFAULT FALSE,
      usado_por_id TEXT,
      criado_em TEXT NOT NULL
    )`,
    `CREATE TABLE IF NOT EXISTS permissions (
      id TEXT PRIMARY KEY,
      aluno_id TEXT NOT NULL,
      livro_id TEXT NOT NULL,
      permitido BOOLEAN NOT NULL,
      observacao TEXT,
      criado_em TEXT NOT NULL,
      atualizado_em TEXT NOT NULL,
      criado_por_id TEXT,
      UNIQUE (aluno_id, livro_id)
    )`,
    `CREATE TABLE IF NOT EXISTS favorites (
      id TEXT PRIMARY KEY,
      usuario_id TEXT NOT NULL,
      livro_id TEXT NOT NULL,
      criado_em TEXT NOT NULL,
      UNIQUE (usuario_id, livro_id)
    )`,
    `CREATE TABLE IF NOT EXISTS reviews (
      id TEXT PRIMARY KEY,
      livro_id TEXT NOT NULL,
      usuario_id TEXT NOT NULL,
      nota INTEGER NOT NULL,
      comentario TEXT NOT NULL,
      criado_em TEXT NOT NULL,
      atualizado_em TEXT,
      UNIQUE (livro_id, usuario_id)
    )`,
    `CREATE TABLE IF NOT EXISTS notices (
      id TEXT PRIMARY KEY,
      titulo TEXT NOT NULL,
      mensagem TEXT NOT NULL,
      categoria TEXT NOT NULL,
      publico TEXT NOT NULL,
      ativo BOOLEAN NOT NULL DEFAULT TRUE,
      destaque BOOLEAN NOT NULL DEFAULT FALSE,
      criado_em TEXT NOT NULL,
      criado_por_id TEXT
    )`,
    `ALTER TABLE books ADD COLUMN IF NOT EXISTS numero_tombo TEXT`,
    `UPDATE books SET numero_tombo = 'SEM-TOMBO-' || id WHERE numero_tombo IS NULL OR numero_tombo = ''`,
    `CREATE UNIQUE INDEX IF NOT EXISTS idx_books_numero_tombo ON books(lower(numero_tombo))`,
    `CREATE INDEX IF NOT EXISTS idx_users_role_ativo ON users(role, ativo)`,
    `CREATE INDEX IF NOT EXISTS idx_users_criado_em ON users(criado_em DESC)`,
    `CREATE INDEX IF NOT EXISTS idx_books_categoria ON books(categoria)`,
    `CREATE INDEX IF NOT EXISTS idx_books_titulo ON books(titulo)`,
    `CREATE INDEX IF NOT EXISTS idx_loans_aluno_status ON loans(aluno_id, status)`,
    `CREATE INDEX IF NOT EXISTS idx_loans_livro_status ON loans(livro_id, status)`,
    `CREATE INDEX IF NOT EXISTS idx_loans_status_data ON loans(status, data_pedido DESC)`,
    `CREATE UNIQUE INDEX IF NOT EXISTS idx_loans_open_unique_student_book ON loans(aluno_id, livro_id) WHERE status IN ('pendente', 'aprovado')`,
    `CREATE INDEX IF NOT EXISTS idx_suggestions_professor ON suggestions(professor_id, criado_em DESC)`,
    `CREATE INDEX IF NOT EXISTS idx_tickets_usuario ON tickets(usuario_id, criado_em DESC)`,
    `CREATE INDEX IF NOT EXISTS idx_tickets_status ON tickets(status)`,
    `CREATE INDEX IF NOT EXISTS idx_teacher_tokens_usado ON teacher_tokens(usado, criado_em DESC)`,
    `CREATE INDEX IF NOT EXISTS idx_permissions_aluno ON permissions(aluno_id, atualizado_em DESC)`,
    `CREATE INDEX IF NOT EXISTS idx_favorites_usuario ON favorites(usuario_id, criado_em DESC)`,
    `CREATE INDEX IF NOT EXISTS idx_reviews_livro ON reviews(livro_id, COALESCE(atualizado_em, criado_em) DESC)`,
    `CREATE INDEX IF NOT EXISTS idx_notices_publico_ativo ON notices(publico, ativo, criado_em DESC)`,
    `CREATE INDEX IF NOT EXISTS idx_notices_destaque ON notices(destaque, ativo, criado_em DESC)`,
  ],
} as const;
