export const libraryEvolutionMigration = {
  id: '002_library_evolution',
  description: 'Uploads, documentos, auditoria e tokens de conta',
  statements: [
    `ALTER TABLE users ADD COLUMN IF NOT EXISTS email_confirmado BOOLEAN NOT NULL DEFAULT TRUE`,
    `ALTER TABLE users ADD COLUMN IF NOT EXISTS email_confirmado_em TEXT`,
    `ALTER TABLE books ADD COLUMN IF NOT EXISTS capa_tipo TEXT NOT NULL DEFAULT 'url'`,
    `ALTER TABLE books ADD COLUMN IF NOT EXISTS capa_arquivo_nome TEXT`,
    `CREATE TABLE IF NOT EXISTS account_tokens (
      id TEXT PRIMARY KEY,
      usuario_id TEXT NOT NULL,
      email TEXT NOT NULL,
      tipo TEXT NOT NULL,
      token_hash TEXT NOT NULL UNIQUE,
      expira_em TEXT NOT NULL,
      usado_em TEXT,
      criado_em TEXT NOT NULL,
      solicitado_ip TEXT
    )`,
    `CREATE INDEX IF NOT EXISTS idx_account_tokens_lookup ON account_tokens(tipo, email, expira_em DESC)`,
    `CREATE INDEX IF NOT EXISTS idx_account_tokens_user ON account_tokens(usuario_id, tipo, expira_em DESC)`,
    `CREATE TABLE IF NOT EXISTS documents (
      id TEXT PRIMARY KEY,
      titulo TEXT NOT NULL,
      descricao TEXT NOT NULL,
      categoria TEXT NOT NULL,
      publico TEXT NOT NULL,
      arquivo_url TEXT NOT NULL,
      arquivo_nome TEXT NOT NULL,
      arquivo_mime TEXT NOT NULL,
      arquivo_tamanho INTEGER NOT NULL,
      ativo BOOLEAN NOT NULL DEFAULT TRUE,
      destaque BOOLEAN NOT NULL DEFAULT FALSE,
      criado_em TEXT NOT NULL,
      atualizado_em TEXT NOT NULL,
      criado_por_id TEXT
    )`,
    `CREATE INDEX IF NOT EXISTS idx_documents_publico_ativo ON documents(publico, ativo, atualizado_em DESC)`,
    `CREATE INDEX IF NOT EXISTS idx_documents_categoria ON documents(categoria, atualizado_em DESC)`,
    `CREATE TABLE IF NOT EXISTS audit_logs (
      id TEXT PRIMARY KEY,
      acao TEXT NOT NULL,
      categoria TEXT NOT NULL,
      descricao TEXT NOT NULL,
      ator_id TEXT,
      ator_nome TEXT,
      ator_role TEXT,
      alvo_tipo TEXT NOT NULL,
      alvo_id TEXT,
      detalhes TEXT,
      criado_em TEXT NOT NULL
    )`,
    `CREATE INDEX IF NOT EXISTS idx_audit_logs_acao ON audit_logs(acao, criado_em DESC)`,
    `CREATE INDEX IF NOT EXISTS idx_audit_logs_ator ON audit_logs(ator_id, criado_em DESC)`,
    `CREATE INDEX IF NOT EXISTS idx_audit_logs_periodo ON audit_logs(criado_em DESC)`,
  ],
} as const;
